const TAG_LABELS: Record<string, string> = {
  abstractions: 'Abstracciones',
  'abuse-prevention': 'Prevención de abusos',
  accessibility: 'Accesibilidad',
  antiforgery: 'Protección antifalsificación',
  'api-design': 'Diseño de API',
  'api-versioning': 'Versionado de API',
  architecture: 'Arquitectura',
  'aspnet-core': 'ASP.NET Core',
  assets: 'Recursos estáticos',
  async: 'Asincronía',
  'async-await': 'Async/await',
  authentication: 'Autenticación',
  authorization: 'Autorización',
  await: 'Await',
  'backend-design': 'Diseño de backend',
  'background-services': 'Servicios en segundo plano',
  backpressure: 'Control de presión',
  behavior: 'Comportamiento',
  blazor: 'Blazor',
  boundaries: 'Fronteras',
  'branded-types': 'Tipos de marca',
  bundling: 'Empaquetado',
  cache: 'Caché',
  caching: 'Caché',
  callbacks: 'Callbacks',
  cancellation: 'Cancelación',
  casts: 'Conversiones de tipo',
  'change-detection': 'Detección de cambios',
  'clean-architecture': 'Arquitectura limpia',
  closures: 'Closures',
  'code-quality': 'Calidad de código',
  'code-review': 'Revisión de código',
  'code-splitting': 'División del código',
  coercion: 'Coerción',
  collections: 'Colecciones',
  communication: 'Comunicación',
  compatibility: 'Compatibilidad',
  completablefuture: 'CompletableFuture',
  'component-design': 'Diseño de componentes',
  components: 'Componentes',
  composables: 'Composables',
  composition: 'Composición',
  'composition-api': 'Composition API',
  computed: 'Computed',
  concurrency: 'Concurrencia',
  'conditional-rendering': 'Renderizado condicional',
  'conditional-types': 'Tipos condicionales',
  configuration: 'Configuración',
  connections: 'Conexiones',
  consistency: 'Consistencia',
  context: 'Contexto',
  contracts: 'Contratos',
  'control-flow': 'Flujo de control',
  controllers: 'Controladores',
  controls: 'Controles',
  coupling: 'Acoplamiento',
  cqrs: 'CQRS',
  cva: 'CVA',
  'data-access': 'Acceso a datos',
  'data-binding': 'Enlace de datos',
  'data-fetching': 'Obtención de datos',
  'data-integrity': 'Integridad de datos',
  'data-loading': 'Carga de datos',
  database: 'Base de datos',
  dates: 'Fechas',
  debugging: 'Depuración',
  'decision-making': 'Toma de decisiones',
  decoupling: 'Desacoplamiento',
  dependencies: 'Dependencias',
  'dependency-injection': 'Inyección de dependencias',
  deployment: 'Despliegue',
  'derived-state': 'Estado derivado',
  design: 'Diseño',
  desktop: 'Escritorio',
  dialogs: 'Diálogos',
  'discriminated-unions': 'Uniones discriminadas',
  domain: 'Dominio',
  'domain-design': 'Diseño de dominio',
  'domain-model': 'Modelo de dominio',
  'domain-rules': 'Reglas de dominio',
  'dotnet-modernization': 'Modernización de .NET',
  dto: 'DTO',
  'dynamic-components': 'Componentes dinámicos',
  editing: 'Edición',
  effects: 'Efectos',
  enterprise: 'Enterprise',
  'entity-framework': 'Entity Framework',
  enums: 'Enums',
  equality: 'Igualdad',
  'error-boundaries': 'Límites de error',
  'error-handling': 'Gestión de errores',
  'es-modules': 'ES Modules',
  'event-loop': 'Event loop',
  events: 'Eventos',
  exceptions: 'Excepciones',
  exhaustiveness: 'Exhaustividad',
  'external-services': 'Servicios externos',
  factories: 'Factorías',
  'feature-design': 'Diseño de funcionalidades',
  'feature-flags': 'Feature flags',
  'feature-routing': 'Rutas por funcionalidad',
  filters: 'Filtros',
  forms: 'Formularios',
  frameworks: 'Frameworks',
  'garbage-collection': 'Recogida de basura',
  gc: 'GC',
  generics: 'Genéricos',
  'graceful-shutdown': 'Apagado ordenado',
  grids: 'Grids',
  guards: 'Guards',
  hardening: 'Refuerzo de seguridad',
  'hardware-integration': 'Integración con hardware',
  hooks: 'Hooks',
  html: 'HTML',
  'html-helpers': 'HTML Helpers',
  http: 'HTTP',
  httpclient: 'HttpClient',
  hydration: 'Hidratación',
  i18n: 'Internacionalización',
  idempotency: 'Idempotencia',
  immutability: 'Inmutabilidad',
  inference: 'Inferencia',
  inject: 'Inject',
  'input-validation': 'Validación de entrada',
  'integration-tests': 'Pruebas de integración',
  interceptors: 'Interceptors',
  interfaces: 'Interfaces',
  interop: 'Interoperabilidad',
  'interview-strategy': 'Estrategia de entrevista',
  invariants: 'Invariantes',
  javascript: 'JavaScript',
  jobs: 'Trabajos en segundo plano',
  json: 'JSON',
  jvm: 'JVM',
  'keep-alive': 'Keep alive',
  'language-features': 'Características del lenguaje',
  latency: 'Latencia',
  layouts: 'Layouts',
  'lazy-loading': 'Carga diferida',
  legacy: 'Legacy',
  libraries: 'Librerías',
  lifecycle: 'Ciclo de vida',
  'lifecycle-hooks': 'Hooks de ciclo de vida',
  lifetimes: 'Lifetimes',
  literals: 'Literales',
  'loading-states': 'Estados de carga',
  logging: 'Registro y trazas',
  maintainability: 'Mantenibilidad',
  'mapped-types': 'Tipos mapeados',
  mapping: 'Mapeo',
  mediatr: 'MediatR',
  memoization: 'Memoización',
  memory: 'Memoria',
  'memory-leaks': 'Fugas de memoria',
  messaging: 'Mensajería',
  metaprogramming: 'Metaprogramación',
  microfrontends: 'Microfrontends',
  microservices: 'Microservicios',
  middleware: 'Middleware',
  migration: 'Migración',
  'minimal-apis': 'Minimal APIs',
  'model-binding': 'Model binding',
  modernization: 'Modernización',
  modularization: 'Modularización',
  modules: 'Módulos',
  monorepo: 'Monorepo',
  multitenancy: 'Multitenencia',
  mutability: 'Mutabilidad',
  mvc: 'MVC',
  navigation: 'Navegación',
  network: 'Red',
  ngrx: 'NgRx',
  objects: 'Objetos',
  observability: 'Observabilidad',
  observables: 'Observables',
  offline: 'Modo sin conexión',
  onpush: 'OnPush',
  oop: 'POO',
  operations: 'Operaciones',
  operators: 'Operadores',
  'optimistic-ui': 'Interfaz optimista',
  orm: 'ORM',
  ownership: 'Responsabilidad clara',
  packaging: 'Empaquetado',
  partials: 'Partials',
  performance: 'Rendimiento',
  pinia: 'Pinia',
  pipeline: 'Pipeline',
  plugins: 'Plugins',
  pooling: 'Pooling',
  preloading: 'Precarga',
  'production-issues': 'Incidencias en producción',
  productivity: 'Productividad',
  profiling: 'Profiling',
  'progressive-enhancement': 'Mejora progresiva',
  promises: 'Promesas',
  props: 'Props',
  prototypes: 'Prototipos',
  'provide-inject': 'Provide/Inject',
  providers: 'Providers',
  queries: 'Consultas',
  queues: 'Colas',
  'race-conditions': 'Condiciones de carrera',
  'rate-limiting': 'Limitación de tasa',
  'razor-pages': 'Razor Pages',
  'react-query': 'React Query',
  reactivity: 'Reactividad',
  'real-world-scenarios': 'Escenarios reales',
  reconciliation: 'Reconciliación',
  redis: 'Redis',
  reducers: 'Reducers',
  refactoring: 'Refactorización',
  reliability: 'Fiabilidad',
  rendering: 'Renderizado',
  renders: 'Renderizados',
  resilience: 'Resiliencia',
  resolvers: 'Resolvers',
  'result-types': 'Tipos de resultado',
  reuse: 'Reutilización',
  routing: 'Enrutamiento',
  runtime: 'Runtime',
  'runtime-validation': 'Validación en runtime',
  rxjs: 'RxJS',
  sanitization: 'Saneado',
  satisfies: 'satisfies',
  scalability: 'Escalabilidad',
  scaling: 'Escalado',
  'schema-generation': 'Generación de esquemas',
  schemas: 'Esquemas',
  scope: 'Alcance',
  security: 'Seguridad',
  'separation-of-concerns': 'Separación de responsabilidades',
  serialization: 'Serialización',
  'server-components': 'Componentes de servidor',
  'server-rendered': 'Renderizado en servidor',
  'server-state': 'Estado del servidor',
  services: 'Servicios',
  'shared-state': 'Estado compartido',
  'shared-types': 'Tipos compartidos',
  'side-effects': 'Efectos secundarios',
  signals: 'Signals',
  ssr: 'SSR',
  ssrf: 'SSRF',
  standalone: 'Standalone',
  startup: 'Arranque',
  state: 'Estado',
  'state-machines': 'Máquinas de estados',
  'state-management': 'Gestión de estado',
  'state-modeling': 'Modelado de estado',
  streams: 'Streams',
  'strict-mode': 'Modo estricto',
  suspense: 'Suspense',
  synchronization: 'Sincronización',
  tables: 'Tablas',
  'tag-helpers': 'Tag Helpers',
  tasks: 'Tareas',
  'test-strategy': 'Estrategia de pruebas',
  testing: 'Pruebas',
  this: 'this',
  threading: 'Threading',
  timezones: 'Zonas horarias',
  tokens: 'Tokens',
  tracing: 'Trazabilidad',
  tracking: 'Seguimiento',
  'trade-offs': 'Compromisos',
  transactions: 'Transacciones',
  transitions: 'Transiciones',
  'type-inference': 'Inferencia de tipos',
  'type-safety': 'Seguridad de tipos',
  'type-system': 'Sistema de tipos',
  types: 'Tipos',
  ui: 'Interfaz',
  'ui-state': 'Estado de la interfaz',
  unknown: 'unknown',
  utilities: 'Utilidades',
  'utility-types': 'Utility Types',
  validation: 'Validación',
  'view-components': 'View Components',
  'view-models': 'View Models',
  views: 'Vistas',
  'virtual-scrolling': 'Desplazamiento virtual',
  virtualization: 'Virtualización',
  'vue-router': 'Vue Router',
  vue3: 'Vue 3',
  watchers: 'Watchers',
  webhooks: 'Webhooks',
  'worker-threads': 'Worker Threads',
  xss: 'XSS',
  zoneless: 'Sin Zone.js',
  zustand: 'Zustand',
};

const WORD_LABELS: Record<string, string> = {
  api: 'API',
  app: 'App',
  aspnet: 'ASP.NET',
  auth: 'autenticación',
  binding: 'enlace',
  cache: 'caché',
  code: 'código',
  component: 'componente',
  components: 'componentes',
  data: 'datos',
  debug: 'depuración',
  design: 'diseño',
  domain: 'dominio',
  error: 'error',
  errors: 'errores',
  event: 'evento',
  events: 'eventos',
  feature: 'funcionalidad',
  features: 'funcionalidades',
  flow: 'flujo',
  forms: 'formularios',
  framework: 'framework',
  hooks: 'hooks',
  http: 'HTTP',
  i18n: 'internacionalización',
  inject: 'Inject',
  integration: 'integración',
  lifecycle: 'ciclo de vida',
  loading: 'carga',
  model: 'modelo',
  models: 'modelos',
  pages: 'Pages',
  performance: 'rendimiento',
  query: 'Query',
  real: 'real',
  render: 'renderizado',
  rendering: 'renderizado',
  router: 'Router',
  routing: 'enrutamiento',
  server: 'servidor',
  services: 'servicios',
  state: 'estado',
  stream: 'stream',
  streams: 'streams',
  tests: 'pruebas',
  type: 'tipo',
  types: 'tipos',
  ui: 'interfaz',
  validation: 'validación',
  view: 'vista',
  views: 'vistas',
  world: 'real',
};

function titleCase(text: string): string {
  return text.replace(/\b\p{L}/gu, (letter) => letter.toLocaleUpperCase('es-ES'));
}

export function humanizeTagSlug(tag: string): string {
  const slug = tag.trim().toLowerCase();

  if (!slug) return '';

  const explicit = TAG_LABELS[slug];
  if (explicit) return explicit;

  const label = slug
    .split('-')
    .map((chunk) => WORD_LABELS[chunk] ?? chunk)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();

  return titleCase(label);
}

export function getTagLabel(tag: string): string {
  return humanizeTagSlug(tag);
}

export function hasTagLabel(tag: string): boolean {
  return Boolean(tag.trim()) && humanizeTagSlug(tag).length > 0;
}
